image:
  repository: ots-django-app
  tag: latest
  pullPolicy: Never

service:
  port: 8000

persistence:
  size: 1Gi
  mountPath: /app/data

ingress:
  enabled: true
  host: 13.203.126.12.nip.io
  clusterIssuer: letsencrypt-prod
