# Generated by Django 5.2 on 2026-02-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0003_alter_result_options_alter_result_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('max_tests_per_day', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower first)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='membership_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='OTS.membershipplan'),
        ),
    ]
