# Generated by Django 5.2 on 2026-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS', '0004_add_membership_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='allowed_question_counts',
            field=models.CharField(default='1,3,5', help_text='Comma-separated test sizes, e.g. 1,3,5 (only these question counts are allowed)', max_length=50),
        ),
    ]
